import "@/styles/globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";

import { AuthProvider } from "@/components/Auth/AuthProvider";
import { NavigationBar } from "@/components/Common/NavigationBar";
import { Toaster } from "@/components/ui/toaster";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR">
      <body className={inter.className}>
        <Toaster />
        <AuthProvider>
          <NavigationBar />
          {children}
        </AuthProvider>
      </body>
    </html>
  );
}
